import { SiteContent } from "./types";

export const movelPlanContent: SiteContent = {
  site: {
    name: "Móvel Plan",
    whatsapp: "5521992032834",
    phoneDisplay: "(21) 99203-2834",
    instagramUrl: "https://www.instagram.com/movel.plan/",
    areas: "Niterói · Barra · Zona Sul",
    logo: "/assets/movel-plan/profile-logo.webp",
  },
  hero: {
    eyebrow: "Niterói · Barra · Zona Sul",
    headline: "Móveis planejados",
    headlineAccent: "sob medida",
    subheadline: "Projetos únicos, desenhados para o seu espaço.",
    primaryButton: "Ver Projetos",
  },
  portfolio: [
    {
      id: "living-room-1",
      title: "Sala planejada",
      category: "Salas",
      image: "/assets/movel-plan/DYPtgxORg-Q-poster.webp",
      video: "/assets/movel-plan/DYPtgxORg-Q.mp4",
      poster: "/assets/movel-plan/DYPtgxORg-Q-poster.webp",
      description: "Ambiente sofisticado integrando sala de estar com marcenaria sob medida de alto padrão.",
      materials: ["MDF Ares", "Off White", "Itapuã"],
      instagramUrl: "https://www.instagram.com/p/DYPtgxORg-Q/",
    },
    {
      id: "kitchen-1",
      title: "Cozinha planejada",
      category: "Cozinhas",
      image: "/assets/movel-plan/DNRSw3zSElq.webp",
      description: "Cozinha funcional com aproveitamento inteligente de espaços e acabamentos premium.",
      materials: ["Marcenaria sob medida"],
      instagramUrl: "https://www.instagram.com/p/DNRSw3zSElq/",
    },
    {
      id: "bedroom-1",
      title: "Quarto planejado",
      category: "Quartos / Closets",
      image: "/assets/movel-plan/DN6JZ30j4nC-poster.webp",
      video: "/assets/movel-plan/DN6JZ30j4nC.mp4",
      poster: "/assets/movel-plan/DN6JZ30j4nC-poster.webp",
      description: "Dormitório com closet integrado, priorizando conforto e organização.",
      materials: ["Marcenaria sob medida"],
      instagramUrl: "https://www.instagram.com/p/DN6JZ30j4nC/",
    },
    {
      id: "bathroom-1",
      title: "Banheiro planejado",
      category: "Banheiros / Lavabos",
      image: "/assets/movel-plan/DOHXUTIknN5-poster.webp",
      video: "/assets/movel-plan/DOHXUTIknN5.mp4",
      poster: "/assets/movel-plan/DOHXUTIknN5-poster.webp",
      description: "Banheiro compacto e funcional com marcenaria resistente a áreas úmidas.",
      materials: ["Ares", "Freijó"],
      instagramUrl: "https://www.instagram.com/p/DOHXUTIknN5/",
    },
    {
      id: "living-room-2",
      title: "Sala planejada",
      category: "Salas",
      image: "/assets/movel-plan/DOOaavrDSEE-poster.webp",
      video: "/assets/movel-plan/DOOaavrDSEE.mp4",
      poster: "/assets/movel-plan/DOOaavrDSEE-poster.webp",
      description: "Painel de TV e armários integrados para sala de estar contemporânea.",
      materials: ["MDF Ares", "Freijó"],
      instagramUrl: "https://www.instagram.com/p/DOOaavrDSEE/",
    },
    {
      id: "bathroom-2",
      title: "Banheiro planejado",
      category: "Banheiros / Lavabos",
      image: "/assets/movel-plan/DNWuNiPp41Z.webp",
      description: "Soluções inteligentes para banheiros e lavabos de todos os tamanhos.",
      materials: ["Marcenaria sob medida"],
      instagramUrl: "https://www.instagram.com/p/DNWuNiPp41Z/",
    },
  ],
  portfolioCategories: ["Todos", "Salas", "Quartos / Closets", "Cozinhas", "Banheiros / Lavabos"],
  contact: {
    eyebrow: "Contato",
    headline: "Vamos planejar o seu próximo ambiente?",
    subheadline: "Conte sua ideia e receba um orçamento sem compromisso.",
    primaryButton: "Conversar no WhatsApp",
    secondaryButton: "Ligar Agora",
  },
};

export const waLink = (whatsapp: string) => `https://wa.me/${whatsapp}`;
